[package]
name = "mnt"
version = "0.2.0"
authors = ["Mickaël Salaün <mickael.salaun@ssi.gouv.fr>"]
description = "List mount points"
repository = "https://github.com/stemjail/mnt-rs"
readme = "README.md"
keywords = ["linux"]
license = "LGPL-3.0"
exclude = [".gitignore"]

[dependencies]
libc = "*"
